
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    String player1,player2;
    int i=0; 
    char A[]=new char[9];
    public frame1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tic-Tac-Toe");         
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        b1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        b9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("Options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("New Game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("Contact Me");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setText("Rules");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void name(String p1,String p2)
    {
        player1=p1;
        player2=p2;
        l1.setText(player1+"'s turn");
    }
    void check()
    {
        if((A[0]=='X'&&A[1]=='X'&&A[2]=='X')||(A[3]=='X' && A[4]=='X'&&A[5]=='X')||(A[6]=='X'&&A[7]=='X'&&A[8]=='X')||(A[0]=='X'&&A[3]=='X'&&A[6]=='X')||(A[1]=='X'&&A[4]=='X'&&A[7]=='X')||(A[2]=='X'&&A[5]=='X'&&A[8]=='X')||(A[0]=='X'&&A[4]=='X'&&A[8]=='X')||(A[2]=='X'&&A[4]=='X'&&A[6]=='X'))
                {    
                    l1.setText("");
                   JOptionPane.showMessageDialog(null,player1+" wins");                   
                  b1.setEnabled(false);b2.setEnabled(false);b3.setEnabled(false);b4.setEnabled(false);b5.setEnabled(false);b6.setEnabled(false);b7.setEnabled(false);b8.setEnabled(false);b9.setEnabled(false);
                }
            else if((A[0]=='O'&&A[1]=='O'&&A[2]=='O')||(A[3]=='O' && A[4]=='O'&&A[5]=='O')||(A[6]=='O'&&A[7]=='O'&&A[8]=='O')||(A[0]=='O'&&A[3]=='O'&&A[6]=='O')||(A[1]=='O'&&A[4]=='O'&&A[7]=='O')||(A[2]=='O'&&A[5]=='O'&&A[8]=='O')||(A[0]=='O'&&A[4]=='O'&&A[8]=='O')||(A[2]=='O'&&A[4]=='O'&&A[6]=='O'))     
               {    
                   l1.setText("");
                   JOptionPane.showMessageDialog(null,player2+" wins");                   
                   b1.setEnabled(false);b2.setEnabled(false);b3.setEnabled(false);b4.setEnabled(false);b5.setEnabled(false);b6.setEnabled(false);b7.setEnabled(false);b8.setEnabled(false);b9.setEnabled(false);
                   
               }
                else if(i==9)
                {   
                    l1.setText("");
                    JOptionPane.showMessageDialog(null,"Draw");                     
                    b1.setEnabled(false);b2.setEnabled(false);b3.setEnabled(false);b4.setEnabled(false);b5.setEnabled(false);b6.setEnabled(false);b7.setEnabled(false);b8.setEnabled(false);b9.setEnabled(false);
                    
                }
                else
                {
                    if(i%2==0)
                        l1.setText(player1+"'s turn");
                    else
                        l1.setText(player2+"'s turn");
                }
    }
    
    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        
        i++;
        if(i%2==0){
            A[4]='O';
            b5.setText("O");
            b5.setBackground(Color.RED);
        }
        else{
            A[4]='X';
            b5.setText("X");
            b5.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b5.getActionListeners())        
            b5.removeActionListener(listener);
        check();
        
    }//GEN-LAST:event_b5ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        
        i++;
        if(i%2==0){
            A[0]='O';
            b1.setText("O");
            b1.setBackground(Color.RED);
        }
        else{
            A[0]='X';
            b1.setText("X");
            b1.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b1.getActionListeners())        
            b1.removeActionListener(listener);        
        check();
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        
        i++;
        if(i%2==0){
            A[1]='O';
            b2.setText("O");
            b2.setBackground(Color.RED);
        }
        else{
            A[1]='X';
            b2.setText("X");
            b2.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b2.getActionListeners())        
            b2.removeActionListener(listener);
        check();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        
        i++;
        if(i%2==0){
            A[2]='O';
            b3.setText("O");
            b3.setBackground(Color.RED);
        }
        else{
            A[2]='X';
            b3.setText("X");
            b3.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b3.getActionListeners())        
            b3.removeActionListener(listener);
        check();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        
        i++;
        if(i%2==0){
            A[3]='O';
            b4.setText("O");
            b4.setBackground(Color.RED);
        }
        else{
            A[3]='X';
            b4.setText("X");
            b4.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b4.getActionListeners())        
            b4.removeActionListener(listener);
        check();
    }//GEN-LAST:event_b4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        
        i++;
        if(i%2==0){
            A[5]='O';
            b6.setText("O");
            b6.setBackground(Color.RED);
        }
        else{
            A[5]='X';
            b6.setText("X");
            b6.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b6.getActionListeners())        
            b6.removeActionListener(listener);
        check();
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        
        i++;
        if(i%2==0){
            A[6]='O';
            b7.setText("O");
            b7.setBackground(Color.RED);
        }
        else{
            A[6]='X';
            b7.setText("X");
            b7.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b7.getActionListeners())        
            b7.removeActionListener(listener);
        check();
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        
        i++;
        if(i%2==0){
            A[7]='O';
            b8.setText("O");
            b8.setBackground(Color.RED);
        }
        else{
            A[7]='X';
            b8.setText("X");
            b8.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b8.getActionListeners())        
            b8.removeActionListener(listener);
        check();
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        
        i++;
        if(i%2==0){
            A[8]='O';
            b9.setText("O");
            b9.setBackground(Color.RED);
        }
        else{
            A[8]='X';
            b9.setText("X");
            b9.setBackground(Color.GREEN);
        }
        for (ActionListener listener : b9.getActionListeners())        
            b9.removeActionListener(listener);
        check();
    }//GEN-LAST:event_b9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        JOptionPane.showMessageDialog(null,"Tic-Tac-Toe Game\nVersion: 1.0.1\nProgram written by Soumyadeep Banerjee\nBSc. (Hons) Computer Science, 1st Year");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        JOptionPane.showMessageDialog(null,"In order to win the game, a player must place three of their marks in a horizontal, vertical or diagonal row.");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        startg ob=new startg();
        ob.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler file:https://twitter.com/SoumyadeepB2001");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Browser not found");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
